version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      java: corretto17
    commands:
      - echo "Install maven dependencies..."
      - mvn install -DskipTests=true

  pre_build:
    commands:
      - echo "Login on ECR..."
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=442042539404.dkr.ecr.us-east-1.amazonaws.com/rudersonvf/portfolio-api
      - IMAGE_TAG=latest

  build:
    commands:
      - echo "Build docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Sending image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
