version: '3.8'

services:
  app:
    image: rudersonvf/portfolio_api:latest
    ports:
      - "8080:8080"
    environment:
      APP_PROFILE: ${APP_PROFILE}
      DB_URL: jdbc:postgresql://103.89.15.163:5432/portfolio_db
      DB_USERNAME: ${PG_DB_USERNAME}
      DB_PASSWORD: ${PG_DB_PASSWORD}
      CORS_ORIGINS: ${CORS}
