name: CI/CD - Production - Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: docker build -t rudersonvf/portfolio_api:latest .

      - name: Push docker image
        run: docker push rudersonvf/portfolio_api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rudersonvf/portfolio_api:latest

      - name: Remove existing container if it exists
        run: |
          if [ "$(docker ps -aq -f name=deploy_portfolio)" ]; then
            docker rm -f deploy_portfolio
          fi

      - name: Run Docker container
        run: |
          docker run -d --name deploy_portfolio \
          -p 8080:8080 \
          -e APP_PROFILE=${{ secrets.APP_PROFILE }} \
          -e DB_URL=jdbc:postgresql://<IP_DA_VM>:5432/seu_banco \
          -e DB_USERNAME=${{ secrets.PG_DB_USERNAME }} \
          -e DB_PASSWORD=${{ secrets.PG_DB_PASSWORD }} \
          -e CORS_ORIGINS=${{ secrets.CORS }} \
          rudersonvf/portfolio_api:latest
