name: CI/CD - Production - Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Docker login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t rudersonvf/portfolio_api .

      - name: Push docker image
        run: docker push rudersonvf/portfolio_api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull img from docker hub
        run: docker pull rudersonvf/portfolio_api:latest

      - name: Run docker container
        run: |
          docker run -d --name deploy_portfolio \
          -p 8080:8080 \
          -e APP_PROFILE=${{secrets.APP_PROFILE}} \
          rudersonvf/portfolio_api
